name: lg
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=2.4.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h5eee18b_5
  - ca-certificates=2024.3.11=h06a4308_0
  - comm=0.2.2=pyhd8ed1ab_0
  - debugpy=1.6.7=py312h6a678d5_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.5.0=h6a678d5_0
  - importlib-metadata=7.1.0=pyha770c72_0
  - importlib_metadata=7.1.0=hd8ed1ab_0
  - ipykernel=6.29.3=pyhd33586a_0
  - ipython=8.22.2=pyh707e725_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jupyter_client=8.6.1=pyhd8ed1ab_0
  - jupyter_core=5.5.0=py312h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=13.2.0=h807b86a_5
  - libgomp=13.2.0=h807b86a_5
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - openssl=3.2.1=hd590300_1
  - parso=0.8.4=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=23.3.1=py312h06a4308_0
  - platformdirs=4.2.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - psutil=5.9.0=py312h5eee18b_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - python=3.12.2=h996f2a0_0
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - pyzmq=25.1.2=py312h6a678d5_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py312h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.12=h1ccaba5_0
  - tornado=6.3.3=py312h5eee18b_0
  - traitlets=5.14.2=pyhd8ed1ab_0
  - typing_extensions=4.11.0=pyha770c72_0
  - tzdata=2024a=h04d1e81_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.41.2=py312h06a4308_0
  - xz=5.4.6=h5eee18b_0
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - aiohttp==3.9.4
      - aiosignal==1.3.1
      - annotated-types==0.6.0
      - anyio==4.3.0
      - attrs==23.2.0
      - black==24.4.0
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - dataclasses-json==0.6.4
      - distro==1.9.0
      - flake8==7.0.0
      - frozenlist==1.4.1
      - greenlet==3.0.3
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - idna==3.7
      - isort==5.13.2
      - jsonpatch==1.33
      - jsonpointer==2.4
      - langchain==0.1.16
      - langchain-community==0.0.32
      - langchain-core==0.1.42
      - langchain-openai==0.1.3
      - langchain-text-splitters==0.0.1
      - langchainhub==0.1.15
      - langsmith==0.1.46
      - marshmallow==3.21.1
      - mccabe==0.7.0
      - multidict==6.0.5
      - mypy-extensions==1.0.0
      - numpy==1.26.4
      - openai==1.17.0
      - orjson==3.10.0
      - packaging==23.2
      - pathspec==0.12.1
      - pycodestyle==2.11.1
      - pydantic==2.7.0
      - pydantic-core==2.18.1
      - pyflakes==3.2.0
      - pyyaml==6.0.1
      - regex==2023.12.25
      - requests==2.31.0
      - sniffio==1.3.1
      - sqlalchemy==2.0.29
      - tenacity==8.2.3
      - tiktoken==0.6.0
      - tqdm==4.66.2
      - types-requests==2.31.0.20240406
      - typing-inspect==0.9.0
      - urllib3==2.2.1
      - yarl==1.9.4
prefix: /home/galkowskim/miniconda3/envs/lg
