[tool.poetry]
name = "sql_azure_openai"
version = "0.1.0"
description = "QA with a SQL database using natural language and AzureOpenAI"
authors = [
    "Mikołaj Gałkowski <mikolaj.galkowski7@gmail.com>",
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
langchain = "^0.1"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.21"

[tool.langserve]
export_module = "sql_azure_openai"
export_attr = "chain"

[tool.templates-hub]
use-case = "sql"
author = "LangChain"
integrations = ["Replicate"]
tags = ["sql"]

[build-system]
requires = [
    "poetry-core",
]
build-backend = "poetry.core.masonry.api"
